name: test pipe
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.9"
            - name: Install
              run: pip install -r req.txt || echo "no requiremtn"
            - name: run test
              run: pytest -v